/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBook = new javax.swing.JLabel();
        txtTitleBook = new javax.swing.JTextField();
        autorBook = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        titleCad = new javax.swing.JLabel();
        genBook = new javax.swing.JLabel();
        txtGenBook = new javax.swing.JTextField();
        noteBook = new javax.swing.JLabel();
        boxNoteBook = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Livros");
        setMinimumSize(new java.awt.Dimension(550, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        titleBook.setText("TÍTULO");
        getContentPane().add(titleBook);
        titleBook.setBounds(100, 120, 80, 16);

        txtTitleBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleBookActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitleBook);
        txtTitleBook.setBounds(100, 140, 330, 22);

        autorBook.setText("AUTOR ");
        getContentPane().add(autorBook);
        autorBook.setBounds(100, 190, 100, 16);

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAutor);
        txtAutor.setBounds(100, 210, 330, 22);

        titleCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleCad.setText("CADASTRO DE LIVROS");
        getContentPane().add(titleCad);
        titleCad.setBounds(160, 60, 202, 25);

        genBook.setText("GÊNERO");
        getContentPane().add(genBook);
        genBook.setBounds(100, 270, 110, 16);
        getContentPane().add(txtGenBook);
        txtGenBook.setBounds(100, 290, 330, 22);

        noteBook.setText("NOTA DE 0 A 10");
        getContentPane().add(noteBook);
        noteBook.setBounds(100, 340, 160, 16);

        boxNoteBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        boxNoteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNoteBookActionPerformed(evt);
            }
        });
        getContentPane().add(boxNoteBook);
        boxNoteBook.setBounds(100, 360, 72, 22);

        jButton1.setText("CADASTRAR LIVRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 400, 169, 40);

        imgFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\RENNAN\\OneDrive\\Documentos\\NetBeansProjects\\BiblioTecla\\PSC\\src\\main\\java\\Lib\\OIG (1).png")); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-90, -10, 660, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleBookActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void boxNoteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNoteBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNoteBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "O livro foi adicionado para sua lista!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorBook;
    private javax.swing.JComboBox<String> boxNoteBook;
    private javax.swing.JLabel genBook;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel noteBook;
    private javax.swing.JLabel titleBook;
    private javax.swing.JLabel titleCad;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGenBook;
    private javax.swing.JTextField txtTitleBook;
    // End of variables declaration//GEN-END:variables
}
